// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRlu50y6f0PhFim7r5dXAfDpqfz0RKTyk',
    appId: '1:622774734842:android:d6fb3079c08f13b3dbde43',
    messagingSenderId: '622774734842',
    projectId: 'flutter-chat-app-475f0',
    storageBucket: 'flutter-chat-app-475f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlHIRtQjH6x8dsL06fT_CNW3Oi-uKs8M',
    appId: '1:622774734842:ios:03bf66ddaf6f2f6adbde43',
    messagingSenderId: '622774734842',
    projectId: 'flutter-chat-app-475f0',
    storageBucket: 'flutter-chat-app-475f0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePzjbjhO8t0R3qs5TsRfrxgq-4pYWI44',
    appId: '1:622774734842:web:b266724f773ca835dbde43',
    messagingSenderId: '622774734842',
    projectId: 'flutter-chat-app-475f0',
    authDomain: 'flutter-chat-app-475f0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-475f0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxlHIRtQjH6x8dsL06fT_CNW3Oi-uKs8M',
    appId: '1:622774734842:ios:03bf66ddaf6f2f6adbde43',
    messagingSenderId: '622774734842',
    projectId: 'flutter-chat-app-475f0',
    storageBucket: 'flutter-chat-app-475f0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePzjbjhO8t0R3qs5TsRfrxgq-4pYWI44',
    appId: '1:622774734842:web:d22ac57555fbb9d8dbde43',
    messagingSenderId: '622774734842',
    projectId: 'flutter-chat-app-475f0',
    authDomain: 'flutter-chat-app-475f0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-475f0.firebasestorage.app',
  );

}